# Generated by Django 3.1 on 2020-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='bmi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bmi',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
