# Generated by Django 3.1 on 2020-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipments',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
