# Generated by Django 3.1 on 2020-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20201118_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='procedure',
            field=models.TextField(null=True),
        ),
    ]
