# Generated by Django 3.1 on 2020-12-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercisehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisehistory',
            old_name='recipe_id',
            new_name='exercise_id',
        ),
    ]
