# Generated by Django 3.1 on 2020-12-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('necessary_ing', models.CharField(max_length=500)),
                ('major_ing', models.CharField(max_length=500)),
                ('ingredients', models.TextField()),
                ('procedure', models.TextField()),
                ('time', models.IntegerField(null=True)),
                ('servings', models.IntegerField(null=True)),
            ],
        ),
    ]
